src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $serie = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_mise_en_marche = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $modele = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_jour = null;

    #[ORM\OneToMany(mappedBy: 'voiture', targetEntity: Location::class)]
    private Collection $locations;

    #[ORM\ManyToOne(inversedBy: 'voitures')]
    private ?Models $models = null;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getSerie(): ?string
    {
        return $this->serie;
    }

    public function setSerie(?string $serie): static
    {
        $this->serie = $serie;

        return $this;
    }

    public function getDateMiseEnMarche(): ?\DateTimeInterface
    {
        return $this->date_mise_en_marche;
    }

    public function setDateMiseEnMarche(?\DateTimeInterface $date_mise_en_marche): static
    {
        $this->date_mise_en_marche = $date_mise_en_marche;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(?string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getPrixJour(): ?float
    {
        return $this->prix_jour;
    }

    public function setPrixJour(?float $prix_jour): static
    {
        $this->prix_jour = $prix_jour;

        return $this;
    }

    /**
     * @return Collection<int, Location>
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): static
    {
        if (!$this->locations->contains($location)) {
            $this->locations->add($location);
            $location->setVoiture($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): static
    {
        if ($this->locations->removeElement($location)) {
            // set the owning side to null (unless already changed)
            if ($location->getVoiture() === $this) {
                $location->setVoiture(null);
            }
        }

        return $this;
    }

    public function getModels(): ?Models
    {
        return $this->models;
    }

    public function setModels(?Models $models): static
    {
        $this->models = $models;

        return $this;
    }
}

src/Form/VoitureForm.php
<?php

namespace App\Form;

use App\Entity\Models;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class VoitureForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('serie', TextType::class)
            ->add('models', EntityType::class, [
                'class' => Models::class,
                'choice_label' => 'label',
                'multiple' => false,
                'expanded' => false,
            ])
            ->add('date_mise_en_marche', DateType::class)
            ->add('prix_jour', TextType::class)
        ;
    }

    public function getName()
    {
        return 'Voiture';
    }
}

src/Controller/VoitureController.php
<?php

namespace App\Controller;

use App\Entity\Voiture;
use App\Form\VoitureForm;
use App\Repository\VoitureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VoitureController extends AbstractController
{
    #[Route('/voiture', name: 'app_voiture')]
    public function listeVoiture(VoitureRepository $vr): Response
    {
        $voitures = $vr->findAll();
        return $this->render('voiture/liste.html.twig', [
            'voitures' => $voitures,
        ]);
    }

    #[Route('/addVoiture', name: 'addVoiture')]
    public function addVoiture(Request $request, EntityManagerInterface $em)
    {
        $voiture = new Voiture();
        $form = $this->createForm(VoitureForm::class, $voiture);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('app_voiture');
        }
        return $this->render('voiture/addVoiture.html.twig', [
            'formV' => $form->createView()
        ]);
    }

    #[Route('/voiture/{id}', name: 'voitureDelete')]
    public function delete($id, EntityManagerInterface $em, VoitureRepository $vr)
    {
        $voiture = $vr->find($id);
        $em->remove($voiture);
        $em->flush();
        return $this->redirectToRoute('app_voiture');
    }

    #[Route('/updateVoiture/{id}', name: 'voitureUpdate')]
    public function edit($id, Request $request, EntityManagerInterface $em, VoitureRepository $vr)
    {
        $voiture = $vr->find($id);
        $form = $this->createForm(VoitureForm::class, $voiture);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($voiture);
            $em->flush();
            return $this->redirectToRoute('app_voiture');
        }
        return $this->render('voiture/updateVoiture.html.twig', [
            'formV' => $form->createView()
        ]);
    }

    #[Route('/searchVoiture', name: 'searchVoiture')]
    public function searchVoiture(Request $request, EntityManagerInterface $entityManager): Response
    {
        $voitures = null;

        if ($request->isMethod('POST')) {
            $search = $request->request->get('input_serie');
            $query = $entityManager->createQuery(
                'SELECT  v FROM App\Entity\Voiture v WHERE v.serie like :serie'
            )
                ->setParameter('serie', '%' . $search . '%');
            $voitures = $query->getResult();
        }
        return $this->render('voiture/rechercheVoiture.html.twig', [
            'voitures' => $voitures
        ]);
    }

    #[Route('/searchVoitureByModel', name: 'searchVoitureByModel')]
    public function searchVoitureByModel(Request $request, EntityManagerInterface $entityManager): Response
    {
        $voitures = null;
        if ($request->isMethod('POST')) {
            $search = $request->request->get('input_model');
            $query = $entityManager->createQuery(
                'SELECT v from App\Entity\Voiture v join v.models m where m.label like :model'
            )
                ->setParameter('model', '%' . $search . '%');
            $voitures = $query->getResult();
        }
        return $this->render('voiture/rechercheVoitureByModels.html.twig', [
            'voitures' => $voitures
        ]);
    }

    #[Route('/getVoitureGroupedByModel', name: 'getVoitureGroupedByModel')]
    public function getVoitureGroupedByModel(Request $request, EntityManagerInterface $entityManager): Response
    {
        $query = $entityManager->createQuery(
            'SELECT m from App\Entity\Models m '
        );
        $voitures = $query->getResult();
        dump($voitures);
        return $this->render('voiture/voitureGroupedByModel.html.twig', [
            'voitures' => $voitures
        ]);
    }
}

templates/voiture/addVoiture.html.twig
<form method="post">
    {{ form_widget(formV) }}
    <input type="submit" value="addVoiture" />
</form>

templates/voiture/liste.html.twig
<h1>Liste des voitures</h1>
<a href="{{ path('addVoiture') }}">Ajouter une voiture</a>
<table border="1">
    <tr>
        <th>Série</th>
        <th>Date Mise en marche</th>
        <td>Model</td>
        <td>Prix jour</td>
        <td>Actions</td>
    </tr>
    {% for v in voitures %}
        <tr>
            <td>{{ v.serie }}</td>
            <td>{{ v.dateMiseEnMarche | date("y-m-d") }}</td>
            <td>{{ v.models.label | default("") }}</td>
            <td>{{ v.prixJour }}</td>
            <td>
                <a href="{{ path('voitureDelete', {'id': v.id}) }}">Supprimer</a>
                <a href="{{ path('voitureUpdate', {'id': v.id}) }}">MAJ</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/voiture/rechercheVoiture.html.twig
<h1>Recherche Voiture</h1>
<form action="" method="post">
    Série: <input type="text" name="input_serie">
    <input type="submit" value="Rechercher">
</form>

{% if voitures is empty %}
Acune voiture trouvée
{% else %}
    <table border="1">
        <tr>
            <th>Serie</th>
            <th>Modele</th>
        </tr>
        {% for voiture in voitures %}
            <tr>
                <td>{{ voiture.serie }}</td>
                <td>{{ voiture.models.label }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

templates/voiture/rechercheVoitureByModels.html.twig
<h1>Recherche Voiture par modèle</h1>
<form action="" method="post">
    Modèle : <input type="text" name="input_model"/>
    <input type="submit" value="Rechercher" name="submit"/>
</form>

{% if voitures is empty %}
Aucune voiture trouvée
{% else %}
<table border="1">
    <tr>
        <th>Série</th>
        <th>Modéle</th>
    </tr>
    {% for voiture in voitures %}
    <tr>
        <td>{{ voiture.serie }}</td>
        <td>{{ voiture.models.label }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

templates/voiture/updateVoiture.html.twig
<h1>MAJ d'une voiture</h1>
<form action="" method="post">
    {{ form_widget(formV) }}
    <input type="submit" value="Modifier">
</form>

templates/voiture/voitureGroupedByModel.html.twig
<h1>Voiture groupé par Modéle</h1>
    <table border="1">
        <tr>
            <th>Modéle</th>
            <th>voitures</th>
        </tr>
        {% for voiture in voitures %}
        <tr>
            <td>{{voiture.label}}</td>
            <td>
                {% for v in voiture.voitures %}
                    {{v.serie}}<br>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>